import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { api, type Product, type StudioAnalytics, type StudioEarnings, type StudioPayout } from "../lib/api";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
import { useToast } from "./Toast";

type Tab = "products" | "analytics" | "profile" | "earnings" | "payouts";

export function ArtisanPage({ onLogout }: { onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("products");
  const [products, setProducts] = useState<Product[]>([]);
  const [analytics, setAnalytics] = useState<StudioAnalytics | null>(null);
  const [earnings, setEarnings] = useState<StudioEarnings | null>(null);
  const [payouts, setPayouts] = useState<StudioPayout[]>([]);
  const [profile, setProfile] = useState<{ studio_name: string; story: string; approved: number } | null>(null);
  const [categories, setCategories] = useState<{ id: string; name: string; slug: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [studioName, setStudioName] = useState("");
  const [story, setStory] = useState("");
  const [saving, setSaving] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [creating, setCreating] = useState(false);
  const [createForm, setCreateForm] = useState({
    title: "",
    description: "",
    priceCents: 199000,
    categoryId: "",
    imageUrl: "",
    stock: 5,
  });

  const fmt = (cents: number) => `₹ ${(cents / 100).toLocaleString("en-IN")}`;
  const { add: toast } = useToast();
  const [aiGenerating, setAiGenerating] = useState(false);
  const [aiPricing, setAiPricing] = useState<{ suggestedMinPaise: number; suggestedMaxPaise: number; reasoning: string } | null>(null);
  const [aiStoryGenerating, setAiStoryGenerating] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [translateLang, setTranslateLang] = useState("");
  const [translateTarget, setTranslateTarget] = useState<string | null>(null);

  useEffect(() => {
    if (tab === "products") {
      setLoading(true);
      api.products.mine().then(setProducts).catch(() => setProducts([])).finally(() => setLoading(false));
    }
    if (tab === "analytics") {
      api.studio.analytics().then(setAnalytics).catch(() => setAnalytics(null));
    }
    if (tab === "earnings") {
      api.studio.earnings().then(setEarnings).catch(() => setEarnings(null));
    }
    if (tab === "payouts") {
      api.studio.payouts().then(setPayouts).catch(() => setPayouts([]));
    }
    if (tab === "profile") {
      api.studio.profile().then((p) => {
        setProfile(p);
        setStudioName(p.studio_name);
        setStory(p.story);
      }).catch(() => {});
    }
    if (tab === "products") {
      api.products.categories().then((rows) => {
        setCategories(rows);
        setCreateForm((current) => ({ ...current, categoryId: current.categoryId || rows[0]?.id || "" }));
      }).catch(() => setCategories([]));
    }
  }, [tab]);

  const saveProfile = async () => {
    setSaving(true);
    try { await api.studio.updateProfile({ studioName, story }); }
    catch { /* offline */ }
    finally { setSaving(false); }
  };

  const generateWithAI = async () => {
    if (!createForm.imageUrl || !createForm.categoryId) {
      toast("Add an image URL and select a category first", "error");
      return;
    }
    setAiGenerating(true);
    try {
      const category = categories.find((c) => c.id === createForm.categoryId);
      const result = await api.ai.generateListing({
        imageUrl: createForm.imageUrl,
        category: category?.name ?? "Decor",
      });
      setCreateForm((cur) => ({
        ...cur,
        title: result.title,
        description: result.description,
        priceCents: result.suggestedPricePaise ?? cur.priceCents,
      }));
      toast("✦ Listing generated by AI");
      // Also get pricing insight
      const pricing = await api.ai.pricingAssist({
        title: result.title,
        category: category?.slug ?? "decor",
        description: result.description,
      });
      setAiPricing(pricing);
    } catch {
      toast("AI generation failed — please try again", "error");
    } finally {
      setAiGenerating(false);
    }
  };

  const generateStory = async () => {
    if (!profile) return;
    setAiStoryGenerating(true);
    try {
      const result = await api.ai.artisanStory({
        studioName: studioName || profile.studio_name,
        craft: "Handmade crafts",
        story: story,
      });
      setStory(result.story);
      toast("✦ Story generated by AI");
    } catch {
      toast("Story generation failed", "error");
    } finally {
      setAiStoryGenerating(false);
    }
  };

  const translateProduct = async (productId: string) => {
    if (!translateLang) { toast("Select a language first", "error"); return; }
    setTranslating(true);
    setTranslateTarget(productId);
    try {
      await api.ai.translate({ productId, targetLanguage: translateLang });
      toast(`✦ Translated to ${translateLang}`);
    } catch {
      toast("Translation failed", "error");
    } finally {
      setTranslating(false);
      setTranslateTarget(null);
    }
  };

  const createProduct = async () => {
    setCreating(true);
    try {
      await api.products.create({
        title: createForm.title,
        description: createForm.description,
        priceCents: createForm.priceCents,
        categoryId: createForm.categoryId,
        image_url: createForm.imageUrl,
        stock: createForm.stock,
      });
      const rows = await api.products.mine();
      setProducts(rows);
      setCreateForm({
        title: "",
        description: "",
        priceCents: 199000,
        categoryId: categories[0]?.id ?? "",
        imageUrl: "",
        stock: 5,
      });
      setCreateOpen(false);
      setAiPricing(null);
      toast("Product published successfully");
    } catch {
      toast("Failed to publish product", "error");
    } finally {
      setCreating(false);
    }
  };

  const tabs: { id: Tab; label: string }[] = [
    { id: "products", label: "Products" },
    { id: "analytics", label: "Analytics" },
    { id: "earnings", label: "Earnings" },
    { id: "payouts", label: "Payouts" },
    { id: "profile", label: "Profile" },
  ];

  // Sparkline data from analytics
  const sparkData = analytics?.topProducts.map((p, i) => ({ name: `P${i + 1}`, sold: p.units_sold })) ?? [];

  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="border-b border-white/10 bg-black/60 backdrop-blur-2xl">
        <div className="mx-auto flex max-w-[1600px] items-center justify-between px-6 py-5 md:px-8">
          <div>
            <p className="text-xs uppercase tracking-[0.35em] text-white/35">klakoach · Artisan Studio</p>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight">{profile?.studio_name ?? "My Studio"}</h1>
          </div>
          <div className="flex items-center gap-3">
            {profile && !profile.approved && (
              <span className="rounded-full border border-yellow-500/30 bg-yellow-500/10 px-3 py-1 text-xs text-yellow-400">
                Pending approval
              </span>
            )}
            <button onClick={onLogout} className="rounded-full bg-[#d4c5a9] px-5 py-3 text-sm font-semibold text-[#1a1510] hover:bg-[#e8dcc4]">
              Logout
            </button>
          </div>
        </div>
      </div>

      <section className="px-4 py-4 md:px-6 md:py-6">
        <div className="mx-auto max-w-[1600px] rounded-4xl border border-white/10 bg-[#0e0e0e] p-4 shadow-[0_40px_120px_rgba(0,0,0,0.5)] md:p-6">
          <div className="grid gap-5 xl:grid-cols-[240px_1fr]">

            {/* Sidebar */}
            <aside className="space-y-4">
              <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                <p className="text-xs uppercase tracking-[0.35em] text-white/40">Studio</p>
                <div className="mt-4 space-y-2">
                  {tabs.map((t) => (
                    <button
                      key={t.id}
                      onClick={() => setTab(t.id)}
                      className={`w-full rounded-2xl px-4 py-4 text-left text-sm transition ${
                        tab === t.id ? "bg-[#d4c5a9] font-semibold text-[#1a1510]" : "bg-black/25 text-white/70 hover:bg-black/40"
                      }`}
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>

              {analytics && (
                <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                  <p className="text-xs uppercase tracking-[0.35em] text-white/40">Quick stats</p>
                  <div className="mt-4 space-y-4">
                    {[
                      ["Revenue", fmt(analytics.totalRevenue)],
                      ["Avg rating", `${analytics.avgRating.avg.toFixed(1)} ★`],
                      ["Reviews", String(analytics.avgRating.count)],
                      ["Low stock", `${analytics.lowStock.length} items`],
                    ].map(([label, value]) => (
                      <div key={label}>
                        <p className="text-xs text-white/35">{label}</p>
                        <p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </aside>

            {/* Main */}
            <div className="space-y-5">
              {/* Products tab */}
              {tab === "products" && (
                <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                  <div className="flex items-center justify-between gap-4">
                    <h2 className="text-3xl font-semibold tracking-tight">Product atelier</h2>
                    <button onClick={() => setCreateOpen((value) => !value)} className="rounded-full bg-[#d4c5a9] px-5 py-3 text-sm font-semibold text-[#1a1510] hover:bg-[#e8dcc4]">
                      + Add product
                    </button>
                  </div>

                  {createOpen && (
                    <div className="mt-6 rounded-[1.75rem] border border-white/10 bg-black/20 p-5">
                      <div className="grid gap-4 md:grid-cols-2">
                        <input
                          className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"
                          placeholder="Title"
                          value={createForm.title}
                          onChange={(e) => setCreateForm((current) => ({ ...current, title: e.target.value }))}
                        />
                        <input
                          className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"
                          placeholder="Image URL"
                          value={createForm.imageUrl}
                          onChange={(e) => setCreateForm((current) => ({ ...current, imageUrl: e.target.value }))}
                        />
                        <textarea
                          rows={4}
                          className="md:col-span-2 rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"
                          placeholder="Description"
                          value={createForm.description}
                          onChange={(e) => setCreateForm((current) => ({ ...current, description: e.target.value }))}
                        />
                        {/* AI Pricing hint */}
                        {aiPricing && (
                          <div className="md:col-span-2 rounded-2xl border border-[#d4a843]/20 bg-[#d4a843]/8 px-5 py-4 text-left">
                            <p className="text-xs font-semibold text-[#d4a843] uppercase tracking-wider mb-2">✦ AI Pricing & Market Insight</p>
                            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#d4a843]/10 pb-3">
                              <div>
                                <p className="text-[11px] text-white/45 uppercase tracking-wider">Suggested Range</p>
                                <p className="text-lg font-semibold text-[#e8dcc4] mt-0.5">
                                  ₹{(aiPricing.suggestedMinPaise / 100).toLocaleString("en-IN")} – ₹{(aiPricing.suggestedMaxPaise / 100).toLocaleString("en-IN")}
                                </p>
                              </div>
                              <div className="flex-1 max-w-[200px] h-1.5 rounded-full bg-white/10 relative overflow-hidden hidden sm:block">
                                <div className="absolute left-[20%] right-[20%] h-full bg-[#d4a843]" />
                              </div>
                            </div>
                            <div className="mt-3 space-y-1.5 text-xs text-white/70">
                              <p><span className="text-[#d4a843] mr-1">Market Position:</span> {aiPricing.reasoning}</p>
                              {(aiPricing as any).marginNote && (
                                <p><span className="text-[#d4a843] mr-1">Cost & Margin Analysis:</span> {(aiPricing as any).marginNote}</p>
                              )}
                            </div>
                          </div>
                        )}
                        <input
                          type="number"
                          className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"
                          placeholder="Price in paise"
                          value={createForm.priceCents}
                          onChange={(e) => setCreateForm((current) => ({ ...current, priceCents: Number(e.target.value) }))}
                        />
                        <input
                          type="number"
                          className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"
                          placeholder="Stock"
                          value={createForm.stock}
                          onChange={(e) => setCreateForm((current) => ({ ...current, stock: Number(e.target.value) }))}
                        />
                        <select
                          className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none"
                          value={createForm.categoryId}
                          onChange={(e) => setCreateForm((current) => ({ ...current, categoryId: e.target.value }))}
                        >
                          <option value="">Select category</option>
                          {categories.map((category) => (
                            <option key={category.id} value={category.id}>{category.name}</option>
                          ))}
                        </select>
                        <div className="flex flex-wrap items-center justify-end gap-3 md:col-span-2">
                          <button
                            type="button"
                            onClick={generateWithAI}
                            disabled={aiGenerating || !createForm.imageUrl || !createForm.categoryId}
                            className="rounded-full border border-[#d4a843]/30 bg-[#d4a843]/10 px-5 py-3 text-sm font-semibold text-[#d4a843] hover:bg-[#d4a843]/20 disabled:opacity-40"
                          >
                            {aiGenerating ? "Generating listing…" : "✦ Generate listing with AI"}
                          </button>
                          <button onClick={() => setCreateOpen(false)} className="rounded-full border border-white/10 px-5 py-3 text-sm text-white/60">
                            Cancel
                          </button>
                          <button
                            onClick={createProduct}
                            disabled={creating || !createForm.title || !createForm.categoryId}
                            className="rounded-full bg-[#d4c5a9] px-5 py-3 text-sm font-semibold text-[#1a1510] disabled:opacity-50"
                          >
                            {creating ? "Publishing…" : "Publish product"}
                          </button>
                        </div>
                      </div>
                    </div>
                  )}

                  {loading ? (
                    <div className="mt-6 grid gap-4 xl:grid-cols-2">
                      {[1, 2, 3, 4].map((i) => <div key={i} className="h-64 animate-pulse rounded-[1.75rem] bg-white/5" />)}
                    </div>
                  ) : products.length === 0 ? (
                    <div className="mt-6 flex h-48 items-center justify-center text-white/30">
                      No products yet. Start the server to load live data.
                    </div>
                  ) : (
                    <div className="mt-6 grid gap-4 xl:grid-cols-2">
                      {products.map((p) => (
                        <motion.div key={p.id} whileHover={{ y: -3 }} className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-black/25">
                          {p.image_url && <img src={p.image_url} alt={p.title} className="h-48 w-full object-cover" />}
                          <div className="p-5">
                            <div className="flex items-center justify-between gap-4">
                              <div>
                                <p className="font-semibold text-white">{p.title}</p>
                                <p className="mt-1 text-sm text-white/40">{p.category}</p>
                              </div>
                              <p className="font-serif text-xl">{fmt(p.price_cents)}</p>
                            </div>
                            <div className="mt-4 flex items-center gap-3">
                              <span className={`rounded-full px-3 py-1 text-xs ${
                                p.stock <= 3 ? "bg-orange-500/20 text-orange-400" : "bg-white/10 text-white/60"
                              }`}>
                                {p.stock} in stock
                              </span>
                              <span className={`rounded-full px-3 py-1 text-xs ${
                                (p as unknown as { status: string }).status === "ACTIVE" ? "bg-green-500/20 text-green-400" : "bg-yellow-500/20 text-yellow-400"
                              }`}>
                                {(p as unknown as { status: string }).status}
                              </span>
                              <div className="ml-auto flex items-center gap-2">
                                <select
                                  value={translateLang}
                                  onChange={(e) => setTranslateLang(e.target.value)}
                                  className="rounded-xl border border-white/10 bg-black/30 px-2 py-1 text-xs text-white/60 outline-none"
                                >
                                  <option value="">Translate…</option>
                                  {["Hindi","Tamil","Bengali","Punjabi","French","German","Spanish"].map((l) => (
                                    <option key={l} value={l}>{l}</option>
                                  ))}
                                </select>
                                {translateLang && (
                                  <button
                                    onClick={() => translateProduct(p.id)}
                                    disabled={translating && translateTarget === p.id}
                                    className="rounded-xl bg-[#d4a843]/20 px-3 py-1 text-xs text-[#d4a843] hover:bg-[#d4a843]/30 disabled:opacity-40"
                                  >
                                    {translating && translateTarget === p.id ? "…" : "✦ Go"}
                                  </button>
                                )}
                              </div>
                            </div>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Analytics tab */}
              {tab === "analytics" && (
                <div className="space-y-5">
                  <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                    <h2 className="mb-6 text-2xl font-semibold tracking-tight">Sales performance</h2>
                    {sparkData.length > 0 ? (
                      <ResponsiveContainer width="100%" height={200}>
                        <AreaChart data={sparkData}>
                          <defs>
                            <linearGradient id="grad" x1="0" y1="0" x2="0" y2="1">
                              <stop offset="5%" stopColor="#d4c5a9" stopOpacity={0.3} />
                              <stop offset="95%" stopColor="#d4c5a9" stopOpacity={0} />
                            </linearGradient>
                          </defs>
                          <XAxis dataKey="name" stroke="#ffffff20" tick={{ fill: "#ffffff40", fontSize: 11 }} />
                          <YAxis stroke="#ffffff20" tick={{ fill: "#ffffff40", fontSize: 11 }} />
                          <Tooltip contentStyle={{ background: "#1a1510", border: "1px solid #d4c5a920", borderRadius: 12 }} />
                          <Area type="monotone" dataKey="sold" stroke="#d4c5a9" fill="url(#grad)" strokeWidth={2} />
                        </AreaChart>
                      </ResponsiveContainer>
                    ) : (
                      <div className="flex h-48 items-center justify-center text-white/30">No sales data yet</div>
                    )}
                  </div>

                  {analytics?.lowStock && analytics.lowStock.length > 0 && (
                    <div className="rounded-4xl border border-orange-500/20 bg-orange-500/5 p-5">
                      <h3 className="mb-4 font-semibold text-orange-400">⚠ Low stock alerts</h3>
                      <div className="space-y-2">
                        {analytics.lowStock.map((item) => (
                          <div key={item.title} className="flex items-center justify-between rounded-xl bg-black/20 px-4 py-3">
                            <p className="text-sm text-white">{item.title}</p>
                            <span className="text-sm text-orange-400">{item.quantity} left</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Profile tab */}
              {tab === "profile" && (
                <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                  <h2 className="mb-6 text-2xl font-semibold tracking-tight">Studio profile</h2>
                  <div className="max-w-lg space-y-4">
                    <div>
                      <label className="mb-2 block text-xs uppercase tracking-[0.2em] text-white/40">Studio name</label>
                      <input
                        className="w-full rounded-2xl border border-white/10 bg-black/30 px-5 py-3 text-sm text-white outline-none focus:border-white/25"
                        value={studioName} onChange={(e) => setStudioName(e.target.value)}
                      />
                    </div>
                    <div>
                      <label className="mb-2 block text-xs uppercase tracking-[0.2em] text-white/40">Your story</label>
                      <textarea
                        rows={5}
                        className="w-full rounded-2xl border border-white/10 bg-black/30 px-5 py-3 text-sm text-white outline-none focus:border-white/25"
                        value={story} onChange={(e) => setStory(e.target.value)}
                      />
                    </div>
                    <button
                      onClick={saveProfile}
                      disabled={saving}
                      className="rounded-full bg-[#d4c5a9] px-8 py-3 text-sm font-semibold text-[#1a1510] hover:bg-[#e8dcc4] disabled:opacity-50"
                    >
                      {saving ? "Saving…" : "Save changes"}
                    </button>
                    <button
                      onClick={generateStory}
                      disabled={aiStoryGenerating}
                      className="rounded-full border border-[#d4a843]/30 bg-[#d4a843]/10 px-8 py-3 text-sm font-semibold text-[#d4a843] hover:bg-[#d4a843]/20 disabled:opacity-40"
                    >
                      {aiStoryGenerating ? "Generating…" : "✦ Generate story with AI"}
                    </button>
                  </div>
                </div>
              )}

              {/* Earnings tab */}
              {tab === "earnings" && (
                <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                  <h2 className="mb-6 text-2xl font-semibold tracking-tight">Earnings</h2>
                  {earnings ? (
                    <div className="space-y-6">
                      <div className="rounded-3xl bg-black/30 p-6">
                        <p className="text-sm text-white/40 mb-1">Lifetime Revenue</p>
                        <p className="text-4xl font-serif text-[#d4c5a9]">{fmt(earnings.lifetimeRevenueCents)}</p>
                      </div>
                      
                      {earnings.dailySeries?.length > 0 && (
                        <div className="rounded-3xl bg-black/30 p-6">
                          <p className="text-sm text-white/40 mb-4">Daily Revenue</p>
                          <ResponsiveContainer width="100%" height={200}>
                            <AreaChart data={earnings.dailySeries}>
                              <defs>
                                <linearGradient id="grad2" x1="0" y1="0" x2="0" y2="1">
                                  <stop offset="5%" stopColor="#d4a843" stopOpacity={0.3} />
                                  <stop offset="95%" stopColor="#d4a843" stopOpacity={0} />
                                </linearGradient>
                              </defs>
                              <XAxis dataKey="date" stroke="#ffffff20" tick={{ fill: "#ffffff40", fontSize: 11 }} />
                              <YAxis stroke="#ffffff20" tick={{ fill: "#ffffff40", fontSize: 11 }} />
                              <Tooltip contentStyle={{ background: "#1a1510", border: "1px solid #d4c5a920", borderRadius: 12 }} />
                              <Area type="monotone" dataKey="revenueCents" stroke="#d4a843" fill="url(#grad2)" strokeWidth={2} />
                            </AreaChart>
                          </ResponsiveContainer>
                        </div>
                      )}

                      <h3 className="font-semibold text-white/80">Revenue by Product</h3>
                      <div className="space-y-3">
                        {earnings.perProduct.map(p => (
                          <div key={p.productId} className="flex justify-between items-center bg-white/5 rounded-2xl p-4">
                            <div>
                              <p className="text-white text-sm font-medium">{p.title}</p>
                              <p className="text-white/40 text-xs">{p.unitsSold} units sold</p>
                            </div>
                            <p className="font-semibold text-[#d4c5a9]">{fmt(p.revenueCents)}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <p className="text-white/30 text-center py-8">Loading earnings...</p>
                  )}
                </div>
              )}

              {/* Payouts tab */}
              {tab === "payouts" && (
                <div className="rounded-4xl border border-white/10 bg-white/4 p-5">
                  <h2 className="mb-6 text-2xl font-semibold tracking-tight">Payouts</h2>
                  {payouts.length > 0 ? (
                    <div className="space-y-3">
                      {payouts.map(p => (
                        <div key={p.id} className="flex justify-between items-center bg-black/30 rounded-2xl p-4">
                          <div>
                            <p className="font-semibold text-[#d4c5a9]">{fmt(p.amountCents)}</p>
                            <p className="text-white/40 text-xs">{new Date(p.createdAt).toLocaleDateString()} · Period: {p.period}</p>
                          </div>
                          <span className={`px-3 py-1 text-xs rounded-full ${p.status === "COMPLETED" ? "bg-green-500/20 text-green-400" : "bg-yellow-500/20 text-yellow-400"}`}>
                            {p.status}
                          </span>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-white/30 text-center py-8">No payouts recorded yet.</p>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
